### PR TITLE
Activate CIP-0018 and CIP-0019

### PR DESCRIPTION
**Pull request by blankey1337**

### CODE REVIEW

**Comment by blankey1337** [comment]
Please do not merge until the time for comments has elapsed.

**Comment by harry1453** [comment]
@4nt1g0 Thanks for your feedback!

In response to the points you raised,

1. The wallet already tracks all user transactions apart from multi-outs so this is an inconsistency in its behaviour which ought to be fixed. Due to the large outcry of users that did not like that the wallet could not independently lookup incoming multi-out transactions, we believe that this should be fixed in the wallet. Regarding redundant information, this is discussed at length in the CIP - I believe that it is a relatively small storage hit in exchange for not having the performance hit of looking up values across all transactions to solve this issue.

2. Yes unfortunately it doesn't, and we have the responsibility of maintaining support for both MariaDB and H2.

3. This is how it will be done internally, although we will need to discuss the issue of indexing transactions that were added to the database before the wallet was updated (as these will remain unindexed.)

4. The database has a type of tables known as derived tables. They are not exchanged on the P2P layer. They are called that because they are derived from the blockchain tables. We can easily create a new derived table for indexing of multi-outs, however we cannot easily modify the transaction table as it forms part of the blockchain. That is why the table contains a multi-purpose attachment field, where multi-out data currently goes.

I hope this addresses your concerns 😄

**Comment by Quibus-burst** [comment]
On #3 i tend to ask myself the same question as @4nt1g0.

When you process a new block and add new transactions to the transaction table you could also process the multi out in that block and add it to your new table. It would be more of a waterfall solution to the code than having another task somewhere else doing something to the transactions. It would be easy to follow in code and would not have any delay.

**Comment by harry1453** [comment]
@Quibus-burst yes I agree with this, we would call:

```java
blockchainProcessor.addListener(this::indexMultiOuts, Event.AFTER_BLOCK_APPLY);
```

However, the network contains nodes whose databases up until the block height at which the node is updated would not be processed, and so all multi-out transactions in the past would not appear on existing nodes without resetting the database and processing it again. This could either be ignored (and anyone who wants to do this can reset their database) or we could implement a background task. Both are viable options.

**Comment by matbogdan79** [comment]
Please make this feature enable/disable trough an config option. It might require allot of RAM and simple home home wallets peers won't handle it and crash.

**Comment by blankey1337** [comment]
@matbogdan79 if I understand it correctly, I don't believe that to be the case. If run during blockchain ingestion, it wouldn't add any additional strain on memory, if anything could make the blockchain download take fractionally longer. @harry1453 please correct me if I'm wrong. I think we are talking about a negligible hit in terms of processing power. The real concern, which is the impact on disk space, has been addressed by OP.

**Comment by harry1453** [comment]
@matbogdan79 There will be a marginal impact on performance and memory usage. However, due to disk space concerns, many individuals have requested that this be an optional change. Due to the demand, we will be making this an optional feature - this will be reflected in the CIP before it is activated.

**Pull request merged**
