### PR TITLE
Activate CIP21

### PR DESCRIPTION
**Pull request by frankTheTank72**
This pull request will serve as the comments thread for this CIP.
Comment period is 10 days, from 07/05/2019 to 17/05/2019.

### CODE REVIEW

**Comment by harry1453** [comment]
The CIP needs to be merged as a draft before it can be considered for activation

**Comment by CurbShifter** [comment]
If the main motivation for this CIP is 

> the assumption of one BURST at one USD as a possible future scenario

Then I would propose to let it rest until 1 burst is at least 0.1 USD and then revaluate
Unless I'm missing something? IMHO. If it's not broken don't fix it.

**Comment by frankTheTank72** [comment]
> The CIP needs to be merged as a draft before it can be considered for activation

in the file it is stated as "draft"

**Comment by harry1453** [comment]
> in the file it is stated as "draft"

you created the PR in the style of an activation PR. normally a draft inclusion does not have a comments period.

**Comment by frankTheTank72** [comment]
> in the file it is stated as "draft"
> 
> you created the PR in the style of an activation PR. normally a draft inclusion does not have a comments period.

oh okay .. just tried to copy the exisitng example (CIP20) - and i thought as a first PR i should do the same like this one….

**Comment by frankTheTank72** [comment]
Can we activate the CIP21 please and add the new fee for assets to the code-base ?
Thanks

**Comment by frankTheTank72** [comment]
@harry1453  how we can go forward with this request pls … what is the next step ?

**Comment by harry1453** [comment]
If there are further small issues like this, please could they be done as one CIP.

**Comment by harry1453** [comment]
To be clear: CIP merged as **draft**. Not yet confirmed or active.

**Comment by frankTheTank72** [comment]
May you add the CIP21 as "Draft" to the end of the list please

image

**Pull request merged**
